#ifndef __ACBLSP_MOVEMENT_ERROR_H__
#define __ACBLSP_MOVEMENT_ERROR_H__ 1
/*=========================================================================
  MovementError.h

    * Movement Error:  
    * Version 0.5

  Thomas M. Eidson
  February, 2013

  Copyright (c) 2012, Hammond Software, Inc.
  =========================================================================*/
#define ACBLSP_MOVEMENT_ERROR_INCORRECT_BOARDS_PLAYED    -502
#define ACBLSP_MOVEMENT_ERROR_REPEAT_BOARDS              -501
#define ACBLSP_MOVEMENT_ERROR_INSUFFICIENT_NUMBER_BOARDS -202
#define ACBLSP_MOVEMENT_ERROR_INCONSISTANT_BOARDS        -201
#define ACBLSP_MOVEMENT_ERROR_INCONSISTENT_ARRAY_SIZES   -200
#define ACBLSP_MOVEMENT_ERROR_DETAIL_END                 -101
#define ACBLSP_MOVEMENT_ERROR_DETAIL_START               -100
#define ACBLSP_MOVEMENT_ERROR_BAROMETER_NOT_MITCHELL     -13
#define ACBLSP_MOVEMENT_ERROR_ONE_WINNER_NOT_MITCHELL    -12
#define ACBLSP_MOVEMENT_ERROR_GAME_TYPE_NOT_MITCHELL     -11
#define ACBLSP_MOVEMENT_ERROR_MITCHELL_DETAIL_PROBLEM    -10
#define ACBLSP_MOVEMENT_ERROR_UNDEFINED                   -2
#define ACBLSP_MOVEMENT_ERROR_NOT_READY                   -1

#define ACBLSP_MOVEMENT_ERROR_READY                        0
#define ACBLSP_MOVEMENT_ERROR_BAD_VERSION               1000
#define ACBLSP_MOVEMENT_ERROR_BAD_FUNCTION              2000
#define ACBLSP_MOVEMENT_ERROR_BAD_TABLE_NUMBER          4000
#define ACBLSP_MOVEMENT_ERROR_BAD_BOARDS_IN_PLAY        5000
#define ACBLSP_MOVEMENT_ERROR_BAD_ROUND_NUMBER          6000
#define ACBLSP_MOVEMENT_ERROR_BAD_BOARDS_PER_ROUND      7000
#define ACBLSP_MOVEMENT_ERROR_BAD_MAX_BOARDS_PLAYED     8000
#define ACBLSP_MOVEMENT_ERROR_BAD_MAX_ROUNDS_PLAYED     9000
#define ACBLSP_MOVEMENT_ERROR_BAD_GAME_TYPE            10000
// unused ACBLSP_MOVEMENT_ERROR_BAD_FILENAME             11000
#define ACBLSP_MOVEMENT_ERROR_BAD_BOARD_1_STARTS       12000
#define ACBLSP_MOVEMENT_ERROR_BAD_EW_PAIR_PLAYING_BOARD_1 13000
#define ACBLSP_MOVEMENT_ERROR_BAD_SKIP_AFTER_THIS_ROUND   14000
#define ACBLSP_MOVEMENT_ERROR_BAD_BYE_STAND               15000
#define ACBLSP_MOVEMENT_ERROR_BAD_BAROMETER               16000
#define ACBLSP_MOVEMENT_ERROR_BAD_PHANTOM_PAIR_NUMBER     17000
#define ACBLSP_MOVEMENT_ERROR_BAD_ONE_WINNER              18000

#endif /* __ACBLSP_MOVEMENT_ERROR_H__ */
